### ISSUE TITLE
Missing README.rst

### ISSUE THREAD

**Issue by WillDignazio** [brandon-rhodes/pyzmq-static#1]
The setup.py script from pypi for pyzmq-static seems to be looking for the README.rst file, fail to find it, and then promptly abort install. It looks like the previous build on swyryan's github used REAMDE.txt. My guess is that it was changed and forgotten about in the setup script. 

The quick fix I have is to comment out the description setting lines (~180) or make them try for a README rather than a direct attempt.

**Comment by borgstrom** [comment]
`README.rst` was missing the from the manifest.

Added in 6f889b5

New version coming to the cheeseshop in a second
